driver: thermal: Remove unused variables.
  error: unused variable 'df' [-Werror,-Wunused-variable]
     92 |         struct devfreq *df = dfc->devfreq;
        |                         ^~

  error: unused variable 'dev' [-Werror,-Wunused-variable]
     93 |         struct device *dev = df->dev.parent;
        |                        ^~
  In the file:
   * drivers/thermal/devfreq_cooling.c

Signed-off-by: Levi Marvin <levimarvin@icloud.com>